name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      cluster:
        description: "Target cluster for deploy"
        type: choice
        required: false
        default: kind
        options:
          - kind
          - minikube

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fix vulnerabilities
        run: npm audit fix || true

      - name: Security audit
        run: npm audit --audit-level=high

      - name: Run tests
        run: npm test || echo "Tests failed"

      - name: Build Docker image
        run: docker build -t hariprasath9849/myapp:latest .

      - name: Login to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        continue-on-error: true

      - name: Push Docker image 
        run: docker push hariprasath9849/myapp:latest
        continue-on-error: true

  kind-test:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.inputs.cluster == 'kind' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Kind cluster
        uses: helm/kind-action@v1.11.0
        with:
          version: v0.22.0
          node_image: kindest/node:v1.30.0

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s --recursive
          kubectl get all -o wide
          kubectl rollout status deployment/myapp-deployment --timeout=120s

      - name: Test Application
        run: |
          kubectl port-forward svc/myapp-service 3000:3000 &
          sleep 10
          curl -f http://localhost:3000/ || exit 1

  minikube-test:
    needs: build-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.cluster == 'minikube' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Minikube
        uses: medyagh/setup-minikube@v0.0.14
        with:
          minikube-version: v1.33.1
          kubernetes-version: v1.30.0

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s --recursive
          kubectl get all -o wide
          kubectl rollout status deployment/myapp-deployment --timeout=120s

      - name: Test Application
        run: |
          kubectl port-forward svc/myapp-service 3000:3000 &
          sleep 10
          curl -f http://localhost:3000/ || exit 1
